project_id = "cwnioogiqacbqunaungs"

[functions.sync-campaigns]
  import_map = "functions/_shared/import_map.json"

# Adiciona a configuração para a nova função de analytics
[functions.sync-analytics]
  import_map = "functions/_shared/import_map.json"